name: CI-CD pipeline

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu:latest
    steps:
    - name: clone the code
      run: echo "clonning the code

  build:
    runs-on: ubuntu:latest
    steps:
      - name: building using docker
        run: echo "Build the code"

  test:
    runs-on: ubuntu:latest
    steps:
      - name: Testing the code
        run: echo "Testing the cases
    
  deploy:
    runs-on: ubuntu:latest
    steps:
      - name: Deploy the pipeline
        run: echo "Deploying the full CI/CD pipeline"
