name: Hello workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: say Hello
        run: echo "Hello from Github Actions!"

      - name: Current Date and Time
        run: date

      - name: Branch name
        run: echo "The current branch is ${{ github.ref_name }}"

      - name: List the files
        run: ls -la

      - name: Runner OS
        run: echo "OS is ${{ runner.os }}"

      - name: Intentional failure
        run: exit 1
