name: manual workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - staging
          - production

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: show environment
        run: echo "Selected environment is ${{ inputs.environment }}"
