name: GitHub Hosted Runners

on:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Runner information
        run: |
          echo "OS is Ubuntu"
          echo "Hostname is $(hostname)"
          echo "user is $($whoami)"

      - name: Installed tools
        run: |
          echo "Docker version is"
          docker --version

          echo "python"
          python3 --version

          echo "Node"
          node --version

          echo "Git"
          git --version


  windows:
    runs-on: windows-latest

    steps:
      - name: Runner information
        run: |
          Write-Output "OS is Windows"
          Write-Output "Hostname is $env:COMPUTERNAME"
          Write-Output "User is $env:USERNAME"

  macos:
    runs-on: macos-latest

    steps:
      - name: Runner information
        run: |
          echo "OS is macOS"
          echo "Hostname is $(hostname)"
          echo "User is $(whoami)"

