name: schedule workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule-job:
    runs-on: ubuntu-latest

    steps:
      - name: schedule workflow
        run: echo "scheduled workflow is running"
